### ISSUE TITLE
Twitter login broken

### ISSUE THREAD

**Issue by coopy** [lukekarrys/gifchess.club#5]
Bug report: 
1. go to http://gifchess.club/
2. click "Sign in with Twitter" or "Login with Twitter"
3. the [auth popup window](https://auth.firebase.com/v2/torid-inferno-617/auth/twitter?&v=js-2.1.1&transport=popup&suppress_status_codes=true) has the following error message:
   
   ```
   {"error":{"code":"ROUTE_NOT_FOUND","message":"Route not found."}}
   ```

Note: the auth window has the following URL: `https://auth.firebase.com/v2/torid-inferno-617/auth/twitter?&v=js-2.1.1&transport=popup&suppress_status_codes=true`

**Comment by lukekarrys** [comment]
Hey thanks for the issue! That twitter app for this got deleted so I just made a new one, so it should be working now :smile:
